// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, en {🇺🇸 English} ko {🇰🇷 Korean} other {Unknown}}"
  },
  "Navigation": {
    "home": "Home",
    "profile": "Profile"
  },
  "NotFoundPage": {
    "title": "Page not found",
    "description": "Please check the URL or use the navigation menu."
  },
  "Error": {
    "title": "Something went wrong!",
    "description": "An error occurred. Please try again."
  },
  "homepage": {
    "description": "Experience interactive Braille learning that adapts to your pace and enhances tactile skills.",
    "getStarted": "Get Started",
    "skipToContent": "Skip to main content",
    "backgroundAriaLabel": "Decorative background showing braille learning environment",
    "getStartedAriaLabel": "Get started with Braille learning",
    "logoAlt": "DotByDot - Interactive Braille Learning Platform"
  },
  "footer": {
    "footerHeading": "Footer",
    "createdBy": "Created By: Chris Heo, Hajo Wolfram, Anthony Chung, Elaine Cui",
    "gitHub": "GitHub",
    "languageSelectAriaLabel": "Select language"
  },
  "auth": {
    "signInTitle": "Sign in to your account",
    "notMember": "Not a member?",
    "registerLink": "Register for Free",
    "emailLabel": "Email address",
    "passwordLabel": "Password",
    "signInButton": "Sign in",
    "signInButtonAria": "Submit sign in form",
    "signinImageAlt": "Illustrative image for sign in page"
  },
  "levelsDashboard": {
    "pageTitle": "Choose a Braille Level",
    "level1LearningTitle": "Level 1: Learning",
    "level1LearningDescription": "Learn the braille representation of each letter.",
    "level1TestTitle": "Level 1: Test",
    "level1TestDescription": "Test your knowledge of the braille alphabet.",
    "level2LearningTitle": "Level 2: Learning",
    "level2LearningDescription": "Practice reading and writing words.",
    "level2TestTitle": "Level 2: Test",
    "level2TestDescription": "Test your knowledge of simple words.",
    "level3ReadingTitle": "Level 3: Reading",
    "level3ReadingDescription": "Learn how to read braille sentences.",
    "level3WritingTitle": "Level 3: Writing",
    "level3WritingDescription": "Learn how to write sentences with braille."
  },
  "levelPage": {
    "level1LearningTitle": "Level 1: Learning",
    "level1LearningDescription": "Learn the braille representation of each letter.",
    "level1TestTitle": "Level 1: Test",
    "level1TestDescription": "Test your knowledge of the braille alphabet.",
    "level2LearningTitle": "Level 2: Learning",
    "level2LearningDescription": "Practice reading and writing words.",
    "level2TestTitle": "Level 2: Test",
    "level2TestDescription": "Test your knowledge of simple words.",
    "level3ReadingTitle": "Level 3: Reading",
    "level3ReadingDescription": "Learn how to read braille sentences.",
    "level3WritingTitle": "Level 3: Writing",
    "level3WritingDescription": "Learn how to write sentences with braille."
  },
  "levelOverview": {
    "start": "Start",
    "startAriaLabel": "Start level"
  },
  "level1Learning": {
    "letters": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "letterCount": "Letter {current} of {total}",
    "instruction": "Read the letter and then type it back:",
    "inputLabel": "Type the letter shown above",
    "inputPlaceholder": "Type the letter",
    "feedbackIncorrect": "❌ Incorrect. Try again!",
    "submit": "Submit",
    "submitAriaLabel": "Submit your answer"
  },
  "level1Test": {
    "letters": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "loadingTest": "Preparing test...",
    "questionCount": "Letter {current} of {total}",
    "instruction": "Read the letter and then type it back:",
    "inputLabel": "Type the letter shown above",
    "inputPlaceholder": "Type the letter",
    "feedbackCorrect": "✅ Correct!",
    "feedbackIncorrectOne": "❌ Incorrect. One more try!",
    "feedbackIncorrectTwo": "❌ Incorrect again.",
    "submit": "Submit",
    "submitAriaLabel": "Submit your answer"
  },
  "level2Learning": {
    "loading": "Loading questions...",
    "loadingFallback": "Loading...",
    "questionCount": "Question {current} of {total}",
    "instruction": "Please read and then spell this word:",
    "inputLabel": "Type your answer here",
    "inputPlaceholder": "Type your answer here",
    "feedbackIncorrect": "❌ Incorrect. Try again!",
    "submit": "Submit Answer",
    "submitAriaLabel": "Submit your answer"
  },
  "level2Test": {
    "loading": "Loading questions...",
    "loadingFallback": "Loading...",
    "questionCount": "Question {current} of {total}",
    "instruction": "Please read and then spell this word:",
    "inputLabel": "Type your answer here",
    "inputPlaceholder": "Type your answer here",
    "feedbackCorrect": "✅ Correct!",
    "feedbackIncorrectOne": "❌ Incorrect. One more try!",
    "feedbackIncorrectTwo": "❌ Incorrect again.",
    "submit": "Submit Answer",
    "submitAriaLabel": "Submit your answer"
  },
  "level3Reading": {
    "loading": "Loading reading activity...",
    "questionCount": "Reading {current} of {total}",
    "inputLabel": "Type your answer here",
    "inputPlaceholder": "Type your answer",
    "feedbackCorrect": "✅ Correct!",
    "feedbackIncorrectOne": "❌ Incorrect. One more try!",
    "feedbackIncorrectTwo": "❌ Incorrect again.",
    "submit": "Submit Answer",
    "submitAriaLabel": "Submit your answer"
  },
  "level3Writing": {
    "loading": "Loading sentences...",
    "questionCount": "Sentence {current} of {total}",
    "instruction": "Read and type this sentence exactly:",
    "inputLabel": "Type your answer here",
    "inputPlaceholder": "Type your answer here",
    "feedbackCorrect": "✅ Correct!",
    "feedbackIncorrectOne": "❌ Incorrect. One more try!",
    "feedbackIncorrectTwo": "❌ Incorrect again.",
    "submit": "Submit Answer",
    "submitAriaLabel": "Submit your answer",
    "errorFetch": "Failed to fetch sentences"
  }
};
export default messages;