// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, en {🇺🇸 English} ko {🇰🇷 Korean} other {Unknown}}"
  },
  "Navigation": {
    "home": "Home",
    "profile": "Profile"
  },
  "NotFoundPage": {
    "title": "Page not found",
    "description": "Please check the URL or use the navigation menu."
  },
  "Error": {
    "title": "Something went wrong!",
    "description": "An error occurred. Please try again."
  },
  "profile": {
    "title": "Your Learning Progress",
    "subtitle": "Track your journey in learning Braille",
    "level": "Level",
    "progress": "Progress"
  },
  "levels": {
    "beginner": "Beginner",
    "intermediate": "Intermediate",
    "advanced": "Advanced"
  },
  "courses": {
    "brailleBasics": "Braille Basics",
    "intermediateBraille": "Intermediate Braille",
    "advancedBraille": "Advanced Braille"
  },
  "LocaleLayout": {
    "title": "dotbydot - Learn Braille",
    "description": "An accessible platform for learning Braille"
  }
};
export default messages;